### ISSUE TITLE
OpenStack Swift / S3: failed to flush, aws-chunked is not supported

### ISSUE THREAD

**Issue by hugoallaine** [grafana/loki#21791]
**Describe the bug**
Logs are not saved into OpenStack Swift using S3 compatible API endpoint.
Can be similar to #21624 as I used v3.6.7 in another cluster and it worked but not sure.

**To Reproduce**
1. Started Loki 3.7.1
2. Started Grafana Alloy v1.16.0
3. Use any query command on Grafana to get logs from Loki

**Expected behavior**
Logs should go to Swift as expected.

**Environment:**
 - Infrastructure: Docker Swarm
 - Deployment tool: Ansible

**Screenshots, Promtail config, or terminal output**
There are a lots of log like this in loki:
`2026-05-07 17:40:34.779	
level=error ts=2026-05-07T15:40:34.750372743Z caller=flush.go:262 component=ingester loop=0 org_id=fake msg="failed to flush" retries=1 err="failed to flush chunks: store put chunk: operation error S3: PutObject, https response error StatusCode: 501, RequestID: tx0dd35daef4274919b0962-0069fcb272, HostID: tx0dd35daef4274919b0962-0069fcb272, api error NotImplemented: Transfering payloads in multiple chunks using aws-chunked is not supported.`

**Comment by Rishabh-1098git** [comment]
I’d like to investigate this issue.

From the error, it looks related to how Loki uploads data to S3-compatible storage in newer versions. I’m going to trace the upload flow and compare the behavior between `v3.6.7` and `v3.7.1` to understand what changed.

**Comment by Rishabh-1098git** [comment]
I've dug into this and found the exact root cause. I've opened a PR with a fix here: #22003.

**The Gist:**
The issue was caused by commit `c83d74893` which added `ChecksumAlgorithm: SHA256` to the `PutObject` call to satisfy AWS Object Lock. When the AWS SDK sees this algorithm without a pre-computed value, it automatically switches to a trailing-checksum mode that wraps the body in `Content-Encoding: aws-chunked`. 

Because OpenStack Swift's S3-compatible API does not support `aws-chunked` encoding, it returns `501 NotImplemented`.

**The Fix:**
If we pre-compute the SHA-256 hash ourselves and pass it in as a plain header (`ChecksumSHA256`), the AWS SDK skips the `aws-chunked` path entirely. This satisfies Object Lock requirements while restoring compatibility for Swift users.

<details>
<summary><b>Click here to read the detailed Root Cause Analysis & Wire-level Proof</b></summary>


## Root Cause Analysis & Proposed Fix

### Background — What Was Fixed Before (PR #21649)

Commit `c83d748936` fixed issue #20088 where AWS S3 buckets with **Object Lock** enabled were rejecting Loki's `PutObject` requests with:

```
InvalidRequest: Content-MD5 OR x-amz-checksum- header is required
for Put Object requests with Object Lock parameters
```

The fix was straightforward — tell the AWS SDK to attach a SHA-256 checksum on every upload:

```go
// pkg/storage/chunk/client/aws/s3_storage_client.go
putObjectInput := &s3.PutObjectInput{
    Body:              readSeeker,
    Bucket:            aws.String(...),
    Key:               aws.String(...),
    StorageClass:      types.StorageClass(a.cfg.StorageClass),
    ChecksumAlgorithm: types.ChecksumAlgorithmSha256, // ← added by #21649
}
```

This worked correctly for real AWS S3. However it introduced a regression for S3-compatible backends like **OpenStack Swift**.

---

### What Is Happening Now (The Regression)

When `ChecksumAlgorithm` is set on `PutObjectInput`, the AWS SDK v2 does **not** simply add a checksum header. Instead it switches to a streaming upload mode called **`aws-chunked`** — an AWS-proprietary protocol where the checksum is sent as an HTTP *trailer* after the body.

This is controlled by `EnableTrailingChecksum: true` which is **hardcoded in the SDK** for all `PutObject` operations (`api_op_PutObject.go:1007`). The relevant middleware decision (`middleware_compute_input_checksum.go:168`):

```go
// SDK internals — not Loki code
if req.IsHTTPS() && !presigning {
    if stream != nil && streamLength != 0 && m.EnableTrailingChecksum {
        // All 3 conditions true → switches to trailing checksum mode
        ctx = v4.SetPayloadHash(ctx, "STREAMING-UNSIGNED-PAYLOAD-TRAILER")
        m.useTrailer = true
        // → AddInputChecksumTrailer middleware then wraps body in aws-chunked
    }
}
```

The resulting HTTP request on the wire looks like:

```
PUT /bucket/my-log-chunk HTTP/1.1
Content-Encoding: aws-chunked                        ← aws-proprietary
x-amz-content-sha256: STREAMING-UNSIGNED-PAYLOAD-TRAILER
x-amz-trailer: x-amz-checksum-sha256
x-amz-decoded-content-length: 1234
Content-Length: 1312

4d2\r\n                       ← hex chunk size
...actual log data...\r\n
0\r\n                         ← end chunk
x-amz-checksum-sha256: ZOyIygCy...=\r\n   ← checksum arrives AFTER body
\r\n
```

**OpenStack Swift's S3-compatible API does not implement the `aws-chunked` protocol.** When it sees `Content-Encoding: aws-chunked` it immediately returns:

```
501 NotImplemented: Transferring payloads in multiple chunks
using aws-chunked is not supported
```

This is the error reported in this issue — `failed to flush chunks: store put chunk: operation error S3: PutObject ... api error NotImplemented`.

---

### Why This Worked in v3.6.x But Broke in v3.7.x

| Version | `ChecksumAlgorithm` set? | SDK behaviour | Swift result |
|---|---|---|---|
| v3.6.x | ❌ Not set | Plain HTTP request, no checksum middleware activated | ✅ Works |
| v3.7.x | ✅ SHA256 (commit `c83d74893`) | Trailing checksum mode → `aws-chunked` encoding | ❌ 501 |

---

### Proposed Fix

The SDK has an intentional early-exit path in the checksum middleware (`middleware_compute_input_checksum.go:131`):

```go
// SDK source comment: "If any checksum header is already set nothing to do."
for header := range req.Header {
    if strings.HasPrefix(strings.ToUpper(header), "X-AMZ-CHECKSUM-") {
        return next.HandleFinalize(ctx, in) // ← returns immediately, skips aws-chunked
    }
}
```

If we pre-compute the SHA-256 ourselves and pass it as `ChecksumSHA256` in the input, the SDK serializer sets the `x-amz-checksum-sha256` header before the middleware runs. The middleware finds the header already present, returns early, and **never activates the `aws-chunked` path**.

**Fix in `pkg/storage/chunk/client/aws/s3_storage_client.go`:**

```go
func (a *S3ObjectClient) PutObject(ctx context.Context, objectKey string, object io.Reader) error {
    return loki_instrument.TimeRequest(ctx, "S3.PutObject", s3RequestDuration, instrument.ErrorCode, func(ctx context.Context) error {
        readSeeker, err := clientutil.ReadSeeker(object)
        if err != nil {
            return err
        }

        // Pre-compute SHA-256 so the SDK sends it as a normal request header
        // instead of an aws-chunked trailer. When ChecksumSHA256 is already
        // set on the input, the SDK's checksum middleware detects the
        // x-amz-checksum-sha256 header and exits early — skipping the
        // aws-chunked encoding path entirely.
        //
        // This satisfies Object Lock's checksum requirement (#20088) while
        // remaining compatible with S3-compatible backends like OpenStack Swift
        // that do not support aws-chunked (#21791).
        //
        // Note: clientutil.ReadSeeker guarantees the body is a bytes.Reader
        // (fully in RAM), so this hash computation involves no extra I/O.
        h := sha256.New()
        if _, err := io.Copy(h, readSeeker); err != nil {
            return err
        }
        sha256Checksum := base64.StdEncoding.EncodeToString(h.Sum(nil))
        if _, err := readSeeker.Seek(0, io.SeekStart); err != nil {
            return err
        }

        putObjectInput := &s3.PutObjectInput{
            Body:              readSeeker,
            Bucket:            aws.String(a.bucketFromKey(objectKey)),
            Key:               aws.String(a.convertObjectKey(objectKey, true)),
            StorageClass:      types.StorageClass(a.cfg.StorageClass),
            ChecksumAlgorithm: types.ChecksumAlgorithmSha256,
            ChecksumSHA256:    aws.String(sha256Checksum), // ← pre-computed
        }
        // ... rest unchanged
    })
}
```

The HTTP request with this fix:

```
PUT /bucket/my-log-chunk HTTP/1.1
Content-Length: 1234
x-amz-checksum-sha256: ZOyIygCy...=    ← simple header, sent upfront
x-amz-content-sha256: <sha256_of_body>

...actual log data...                  ← raw body, no chunking
```

Both AWS S3 and OpenStack Swift accept this format. ✅

---

### Does This Fix Both Problems?

| Scenario | Before #21649 | After #21649 (broken) | With this fix |
|---|---|---|---|
| AWS S3 (standard) | ✅ | ✅ | ✅ |
| AWS S3 + Object Lock | ❌ Missing checksum | ✅ | ✅ |
| OpenStack Swift | ✅ | ❌ 501 aws-chunked | ✅ |
| MinIO / other S3-compat | ✅ | ❌ (if no aws-chunked support) | ✅ |

---

### Tradeoffs & Risks

**Performance:** `clientutil.ReadSeeker()` already buffers the entire chunk body into a `bytes.Reader` in RAM before `PutObject` is called. The SHA-256 computation reads this in-memory buffer — there is no extra network or disk I/O. For typical Loki chunk sizes (compressed, usually under a few MB) this adds negligible latency.

**Correctness:** The checksum value is identical to what the SDK would compute internally. AWS S3 spec accepts the checksum as either a header or a trailer — both are valid.

**Object Lock:** AWS Object Lock requires `Content-MD5` OR an `x-amz-checksum-*` header. This fix sends `x-amz-checksum-sha256` as a normal header, which fully satisfies the requirement.

**Scope:** The change is contained to a single function in one file. No config changes, no new dependencies beyond stdlib (`crypto/sha256`, `encoding/base64`).

**Additional imports needed:**
```go
"crypto/sha256"
"encoding/base64"
```

</details>
