### PR TITLE
Updated README to mention the required go version for build.

### PR DESCRIPTION
**Pull request by adityacs**
Go 1.10+ version is required. I was trying to build using 1.9 and it failed with below error
`# github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/aws
vendor/github.com/cortexproject/cortex/pkg/chunk/aws/dynamodb_storage_client.go:691:9: undefined: strings.Builder`

string.Builder is available only after 1.10 version.

### CODE REVIEW

**Comment by gouthamve** [comment]
Thanks!
